### ISSUE TITLE
Validated + Semantic Types are awkward to use

### ISSUE THREAD

**Issue by sazzer** [pksilen/validated-types#1]
Firstly, this package fills a hole, especially for DDD-style applications where it becomes important to be able to guarantee that a variable is valid. So that's awesome :)

However, using both Validated and Semantic Types together is slightly more awkward than it would ideally be. Both in terms of creating the values, but more so in terms of using them.

Creating a new Validated+Semantic Type is this:
```
type ValidatedName = VString<`1,300`>;
const nameVSpec: VSpecOf<ValidatedName> = '1,300';
export type Name = SemType<ValidatedName, 'name'>;
```

Which is fine.

Creating a new instance of it, however, is this:
```
export function newName(input: string): Name {
  const validatedName: ValidatedName = VString.tryCreate(nameVSpec, input);

  return new SemType({ 'name': validatedName });
}
```

Which isn't too bad, but feels like it could be a bit easier.

Using it, however, is this:
```
  const result = newName(input);

  expect(result.value.value).toEqual(expected);
```

Note the requirement to have `result.value.value` to dereference the value twice. That's not instantly obvious and just feels a bit clunky.

Given that both `SemType` and `VString` are classes, it would be nice if there was some way to get the innermost value in a single step without needing the double de-reference.

Cheers

**Comment by pksilen** [comment]
Hi, 
I can make some improvements. I'll let you know in 1-2 days.

**Comment by pksilen** [comment]
Hi,
I have created a new version of the library: 1.7.0

It will contain following new types:
- SemVInt
- SemVFloat
- SemVString

You can use them like this:

```ts
import { SemVInt } from 'validated-types';

type HttpPort = SemVInt<'httpPort', '1,65535'>;
const httpPort: HttpPort = SemVInt.tryCreate('httpPort', '1,65535', 8080);
console.log(httpPort.value); // Prints 8080
```

```ts
import { SemVFloat } from 'validated-types';

type LoanInterest = SemVFloat<'loanInterest', '0,100'>;
const loanInterest: LoanInterest = SemVFloat.tryCreate('loanInterest', '0,100', 4.99);
console.log(loanInterest.value); // Prints 4.99
```

```ts
import { SemVString } from 'validated-types';

type LoginUrl = SemVString<'loginUrl', '1,8192,url'>;
const loginUrl: LoginUrl = SemVString.tryCreate('loginUrl', '1,8192,url', "https://server.com");
console.log(loginUrl.value) // Prints https://server.com
```
